all:
  children:
    webservers:
      hosts:
        web01:
        web02:
    databases:
      hosts:
        db01:
  vars:
    ansible_user: ansible
    ansible_password: ansible
    ansible_become_password: ansible
